// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCybXsAnaVJrCQQxoQvAH6rtlThimiaxlI',
    appId: '1:375389492440:web:1fd2f0f761d3388c3573ad',
    messagingSenderId: '375389492440',
    projectId: 'forms-af0d2',
    authDomain: 'forms-af0d2.firebaseapp.com',
    databaseURL: 'https://forms-af0d2-default-rtdb.firebaseio.com',
    storageBucket: 'forms-af0d2.appspot.com',
    measurementId: 'G-7XBH7859QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8EjEy5uFcUL5_SgM93FiW1-8fO3ZUUpo',
    appId: '1:375389492440:android:8919d0e7530784c63573ad',
    messagingSenderId: '375389492440',
    projectId: 'forms-af0d2',
    databaseURL: 'https://forms-af0d2-default-rtdb.firebaseio.com',
    storageBucket: 'forms-af0d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrL0dj7Bvph9O6rUe7Jfms580IwYdFXfE',
    appId: '1:375389492440:ios:3182917d1bbd17af3573ad',
    messagingSenderId: '375389492440',
    projectId: 'forms-af0d2',
    databaseURL: 'https://forms-af0d2-default-rtdb.firebaseio.com',
    storageBucket: 'forms-af0d2.appspot.com',
    iosBundleId: 'com.example.norandyApp',
  );
}
